version: '3'

services:
  geodb:
    image: mdillon/postgis
    restart: always
    networks:
      - backend
    volumes:
      - geodb-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: localdev
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: chi77
    expose:
      - "5432"
    ports:
      - "5432:5432"

  django:
    image: togetherchicago/chi77-django
    tty: true
    build: .
    command: ["scripts/wait_for_it.sh", "geodb:5432", "--", "scripts/init_django.sh"]
    networks:
      - backend
    volumes:
      - .:/django
    ports:
      - "5000:5000"
    depends_on:
      - geodb

  frontend:
    image: togetherchicago/chi77-frontend
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

volumes:
  geodb-volume:
  node-modules:

networks:
  backend:
