version: '3'

services:
  geodb:
    image: mdillon/postgis
    restart: always
    volumes:
      - "geodb-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: localdev
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: chi77
    expose:
      - "5432"
    ports:
      - "5432:5432"

  django:
    build: .
    command: bash -c "sleep 15 && ./scripts/init_db.sh && ./scripts/init_django.sh  && python manage.py runserver 0.0.0.0:5000"
    volumes:
      - .:/django
    ports:
      - "5000:5000"
    depends_on:
      - geodb

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  geodb-volume:
  node-modules:
