version: '3'

services:
  geodb:
    image: mdillon/postgis
    restart: always
    volumes:
      - "geodb-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: localdev
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: chi77
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  geodb-volume:
