version: '3'

services:
  geodb:
    build: ./geodb/
    restart: always
    volumes:
      - "geodb-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: chi77
      POSTGRES_PASSWORD: gispass
    expose:
      - "5432"

  django:
    build: ./web/
    command: bash ./startup.sh
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - geodb

volumes:
  geodb-volume:
