"""
Query Operators
"""
QUERY_WHERE = "$where"
QUERY_SELECT = "$select"
QUERY_ORDER_BY = "$orderBy"
QUERY_LIMIT = "$limit"
QUERY_OFFSET = "$offset"

QUERY_AND = "$and"
QUERY_OR = "$or"

VALID_QUERY_OPERATORS = [ QUERY_WHERE, QUERY_SELECT, QUERY_ORDER_BY, QUERY_LIMIT, QUERY_OFFSET ]
