# Generated by Django 2.0.2 on 2018-02-04 01:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_area', models.CharField(max_length=64)),
                ('pri_neigh', models.CharField(max_length=64)),
                ('sec_neigh', models.CharField(max_length=64)),
                ('shape_len', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Precincts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_area', models.CharField(max_length=64)),
                ('precinct', models.CharField(max_length=64)),
                ('ward', models.CharField(max_length=64)),
                ('full_text', models.CharField(max_length=64)),
                ('shape_len', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Tracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statefp10', models.CharField(max_length=64)),
                ('name10', models.CharField(max_length=64)),
                ('commarea_n', models.CharField(max_length=64)),
                ('namelsad10', models.CharField(max_length=64)),
                ('commarea', models.CharField(max_length=64)),
                ('geoid10', models.CharField(max_length=64)),
                ('notes', models.CharField(max_length=64)),
                ('tractce10', models.CharField(max_length=64)),
                ('countyfp10', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=64)),
                ('shape_area', models.CharField(max_length=64)),
                ('shape_leng', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Zips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.CharField(max_length=64)),
                ('shape_len', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=64)),
                ('shape_area', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
