# Generated by Django 2.0.2 on 2018-10-30 22:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('domain_name', models.CharField(default='', max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
