# Generated by Django 2.0.2 on 2018-11-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalency',
            name='geom_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geom_a', to='chicagomap.Domain'),
        ),
        migrations.AlterField(
            model_name='equivalency',
            name='geom_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geom_b', to='chicagomap.Domain'),
        ),
    ]
