# Generated by Django 2.0.2 on 2018-12-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rank', models.IntegerField(null=True)),
            ],
        ),
    ]
