# Generated by Django 2.0.2 on 2018-11-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0002_auto_20181103_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalency',
            name='pct',
            field=models.FloatField(null=True),
        ),
    ]
