# Generated by Django 2.0.2 on 2018-02-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0003_auto_20180204_0212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Neighborhoods',
            new_name='Neighborhood',
        ),
        migrations.RenameModel(
            old_name='Precincts',
            new_name='Precinct',
        ),
        migrations.RenameModel(
            old_name='Tracts',
            new_name='Tract',
        ),
        migrations.RenameModel(
            old_name='Wards',
            new_name='Ward',
        ),
        migrations.RenameModel(
            old_name='Zips',
            new_name='Zip',
        ),
    ]
