# Generated by Django 2.0.2 on 2018-02-05 00:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0004_auto_20180204_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodToPrecinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_coverage', models.DecimalField(decimal_places=60, max_digits=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chicagomap.Neighborhood')),
                ('precinct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chicagomap.Precinct')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodToTract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_coverage', models.DecimalField(decimal_places=60, max_digits=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chicagomap.Neighborhood')),
                ('tract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chicagomap.Tract')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodToWard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_coverage', models.DecimalField(decimal_places=60, max_digits=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chicagomap.Neighborhood')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chicagomap.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodToZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_coverage', models.DecimalField(decimal_places=60, max_digits=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chicagomap.Neighborhood')),
                ('zip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chicagomap.Zip')),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='precincts',
            field=models.ManyToManyField(through='chicagomap.NeighborhoodToPrecinct', to='chicagomap.Precinct'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='tracts',
            field=models.ManyToManyField(through='chicagomap.NeighborhoodToTract', to='chicagomap.Tract'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='wards',
            field=models.ManyToManyField(through='chicagomap.NeighborhoodToWard', to='chicagomap.Ward'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='zips',
            field=models.ManyToManyField(through='chicagomap.NeighborhoodToZip', to='chicagomap.Zip'),
        ),
    ]
