# Generated by Django 2.0.2 on 2018-02-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0005_auto_20180205_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhoodtoprecinct',
            name='neighborhood_coverage',
        ),
        migrations.RemoveField(
            model_name='neighborhoodtotract',
            name='neighborhood_coverage',
        ),
        migrations.RemoveField(
            model_name='neighborhoodtoward',
            name='neighborhood_coverage',
        ),
        migrations.RemoveField(
            model_name='neighborhoodtozip',
            name='neighborhood_coverage',
        ),
    ]
