# Generated by Django 2.0.2 on 2018-03-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0008_auto_20180308_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='id',
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zip',
            name='zip',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
