# Generated by Django 2.0.2 on 2018-03-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0009_auto_20180315_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhoodtoprecinct',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='neighborhoodtotract',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='neighborhoodtoward',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='neighborhoodtozip',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tracttoprecinct',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='wardtotract',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ziptoprecinct',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ziptotract',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ziptoward',
            name='pct',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
