# Generated by Django 2.0.2 on 2018-03-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicagomap', '0011_auto_20180323_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoodtoprecinct',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhoodtotract',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhoodtoward',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhoodtozip',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tracttoprecinct',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='wardtotract',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ziptoprecinct',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ziptotract',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ziptoward',
            name='pct',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
