# Generated by Django 2.0.2 on 2018-02-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_tract', models.FloatField(default=0.0)),
                ('pop_100', models.IntegerField(default=0)),
            ],
        ),
    ]
