# Generated by Django 2.0.2 on 2019-09-25 22:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ingested', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('domain_name', models.CharField(default='', max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Equivalency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersection', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('pct_a', models.FloatField(null=True)),
                ('pct_b', models.FloatField(null=True)),
                ('geom_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geom_a', to='getdata.Domain')),
                ('geom_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geom_b', to='getdata.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256, null=True)),
                ('domain_name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date_ingested', models.DateField(null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getdata.Dataset')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.Domain')),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getdata.Indicator')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.Indicator'),
        ),
    ]
