# Generated by Django 2.0.2 on 2018-10-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getdata.Dataset'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getdata.Indicator'),
        ),
    ]
