# Generated by Django 2.0.2 on 2018-02-24 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='census_tract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicagomap.Tract'),
        ),
    ]
