# Generated by Django 2.0.2 on 2018-11-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='domain_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
