# Generated by Django 2.0.2 on 2018-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_auto_20180224_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
